### ISSUE TITLE
 AttributeError: 'TransactionManager' object has no attribute 'runner'

### ISSUE THREAD

**Issue by waelemara** [SvenskaSpel/locust-plugins#17] opened 2020-08-25 12:30 UTC
I'm trying to use TransactionManager and I'm following the example in the repo, however when I call tm.strart_transaction I receive this error 
` AttributeError: 'TransactionManager' object has no attribute 'runner'`

here is the full traceback
` Traceback (most recent call last):
worker_1  |   File "/usr/local/lib/python3.8/site-packages/locust/user/task.py", line 284, in run
worker_1  |     self.execute_next_task()
worker_1  |   File "/usr/local/lib/python3.8/site-packages/locust/user/task.py", line 309, in execute_next_task
worker_1  |     self.execute_task(self._task_queue.pop(0))
worker_1  |   File "/usr/local/lib/python3.8/site-packages/locust/user/task.py", line 321, in execute_task
worker_1  |     task(self)
worker_1  |   File "/mnt/locust/test_scenarios/simulate_compliance_life_cycle.py", line 188, in create_compliance
worker_1  |     self.tm.start_transaction("compliance_creation")
worker_1  |   File "/home/locust/.local/lib/python3.8/site-packages/locust_plugins/transaction_manager.py", line 46, in start_transaction
worker_1  |     transaction["user_count"] = self.runner.user_count if self.runner else 0
worker_1  | AttributeError: 'TransactionManager' object has no attribute 'runner'
`

I'm using locust version 1.1.1 and locust.plugins version 1.0.15

Appreciate your support.

**Comment by cyberw** [comment] 2020-08-25 13:09
@howardosborne can you take a look at this?

**Comment by howardosborne** [comment] 2020-08-25 14:20
will do

**Comment by howardosborne** [comment] 2020-08-25 14:46
> I'm trying to use TransactionManager and I'm following the example in the repo, however when I call tm.strart_transaction I receive this error
> ` AttributeError: 'TransactionManager' object has no attribute 'runner'`
> 
> here is the full traceback
> `Traceback (most recent call last): worker_1 | File "/usr/local/lib/python3.8/site-packages/locust/user/task.py", line 284, in run worker_1 | self.execute_next_task() worker_1 | File "/usr/local/lib/python3.8/site-packages/locust/user/task.py", line 309, in execute_next_task worker_1 | self.execute_task(self._task_queue.pop(0)) worker_1 | File "/usr/local/lib/python3.8/site-packages/locust/user/task.py", line 321, in execute_task worker_1 | task(self) worker_1 | File "/mnt/locust/test_scenarios/simulate_compliance_life_cycle.py", line 188, in create_compliance worker_1 | self.tm.start_transaction("compliance_creation") worker_1 | File "/home/locust/.local/lib/python3.8/site-packages/locust_plugins/transaction_manager.py", line 46, in start_transaction worker_1 | transaction["user_count"] = self.runner.user_count if self.runner else 0 worker_1 | AttributeError: 'TransactionManager' object has no attribute 'runner'`
> 
> I'm using locust version 1.1.1 and locust.plugins version 1.0.15
> 
> Appreciate your support.

Hi Wael,

Two things:
1. Does the example work for you?
2. Could you share simulate_compliance_life_cycle.py?
Thanks

**Comment by waelemara** [comment] 2020-08-26 01:36
Hi I tried the example, as is, and I'm getting the same error 
`worker_1  | 'TransactionManager' object has no attribute 'runner'
worker_1  | Traceback (most recent call last):
worker_1  |   File "/usr/local/lib/python3.8/site-packages/locust/user/task.py", line 284, in run
worker_1  |     self.execute_next_task()
worker_1  |   File "/usr/local/lib/python3.8/site-packages/locust/user/task.py", line 309, in execute_next_task
worker_1  |     self.execute_task(self._task_queue.pop(0))
worker_1  |   File "/usr/local/lib/python3.8/site-packages/locust/user/task.py", line 321, in execute_task
worker_1  |     task(self)
worker_1  |   File "/mnt/locust/test_scenarios/tm.py", line 11, in home
worker_1  |     self.tm.start_transaction("startup")
worker_1  |   File "/home/locust/.local/lib/python3.8/site-packages/locust_plugins/transaction_manager.py", line 46, in start_transaction
worker_1  |     transaction["user_count"] = self.runner.user_count if self.runner else 0
worker_1  | AttributeError: 'TransactionManager' object has no attribute 'runner'
`

**Comment by howardosborne** [comment] 2020-08-26 10:57
OK, thanks.
One more thing, do you get the error when running locust standalone (not master/worker)?

**Comment by waelemara** [comment] 2020-08-26 10:59
When I run in a master worker setup. On our local machines we do that as well using docker containers.

**Comment by waelemara** [comment] 2020-08-26 11:00
Also note I haven't tried standalone.

**Comment by howardosborne** [comment] 2020-08-26 13:02
Hi, sorry but, I haven't been able to recreate the issue either locally or on an instance in AWS.

It would be really good to get to the bottom of it, so could you let me know how you get on with your standalone run?

Thanks

**Comment by waelemara** [comment] 2020-08-26 23:24
I can confirm that it is working in a standalone mode, in the example and in my real test class.

**Comment by waelemara** [comment] 2020-08-26 23:35
Do you think running in locust 1.1.1 in distributed mode would be a factor to this?

**Comment by howardosborne** [comment] 2020-08-27 07:39
No, I can run the example in distributed mode across vanilla machines in AWS.

(BTW, we are now up to version 1.2.2)

The Transaction Manager relies on the init event being fired to provide a reference to the runner - so I'm guessing the issue is around here, but I'd be really useful to recreate your problem.

Are all your instances running in Docker containers?

**Comment by waelemara** [comment] 2020-09-03 10:06
Hi sorry, it took a bit of time to come back to this, we upgraded to the latest locust version 1.2.3. and the issue is still happening.
Yes, we run in docker containers.
Also, one more thing to note, we use locust as a library, and we don't use the locust command line to run in distributed mode.

**Comment by waelemara** [comment] 2020-09-03 10:07
This is the code for the startup_worker 
`    print("I'm worker")
    parser = TestScenariosParser()
    (user_classes, tags, data_count_per_vu) = parser.parse_arguments()
    DataSetting.data_count_per_virtual_user = data_count_per_vu

    print("start to retrieve data partition")
    receiver = Receiver(master_host=MASTER_HOST)
    receiver.receive()

    print("start to create worker runner")
    env = Environment(user_classes=user_classes, tags=tags)
    env.create_worker_runner(master_host=MASTER_HOST, master_port=5557)

    env.runner.greenlet.join()`

**Comment by howardosborne** [comment] 2020-09-05 15:02
Thanks for that.
Well the good news is I can reproduce the error.
The bad news is it may take a while to fix, so in the meantime, please run the clients with the command line which should work fine.

**Comment by waelemara** [comment] 2020-09-08 01:53
Ohh it is nice that you were able to reproduce the bug.

**Comment by waelemara** [comment] 2020-09-09 04:29
Also if it is ok do you mind explaining the differences between the two approaches in running locust when it comes to injecting the runner.

**Comment by howardosborne** [comment] 2020-09-12 14:17
Hi, sorry for not coming back sooner - I'm a tad busy at the moment...

The issue is with locust events (which the TransactionManager relies on) not being fired when running as a library.

I'm looking into fixes (and workarounds) and will come back to you when I have something. In the meantime, you'll need to run 'locust -f'

**Comment by cyberw** [comment] 2020-09-30 06:53
@howardosborne Is this fixed by #20 ?

**Comment by howardosborne** [comment] 2020-09-30 07:15
> @howardosborne Is this fixed by #20 ?

Yes

**Closed** 2020-09-30 07:16 UTC
