### ISSUE TITLE
Paho-MQTT raises BAD_LENGTH exception

### ISSUE THREAD

**Issue by j04n-f** [SvenskaSpel/locust-plugins#143] opened 2023-08-30 08:05 UTC
## Description

We use Locust and Paho-MQTT to load test an IoT system. The system uses TLS. After few minutes, Paho-MQTT raises the following error:

```
Exception in thread Thread-2 (_thread_main):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
         ^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 1181, in _loop
    rc = self.loop_write()
         ^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 1577, in loop_write
    rc = self._packet_write()
         ^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 2464, in _packet_write
    write_length = self._sock_send(
                   ^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/paho/mqtt/client.py", line 649, in _sock_send
    return self._sock.send(buf)
           ^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/gevent/ssl.py", line 508, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLError: [SSL: BAD_LENGTH] bad length (_ssl.c:2423)
```

## Example

We reproduced the exception using the Mosquitto test broker and a TLS connection. The error is not reproducible using a non-encrypted port (e.g. 1883):

```python
import json
import ssl
import time

from locust import task, TaskSet
from locust.user.wait_time import between
from locust_plugins.users.mqtt import MqttUser

tls_context = ssl.SSLContext(ssl.PROTOCOL_TLS)
tls_context.load_cert_chain("client.crt", "client.key")
tls_context.load_verify_locations("mosquitto.org.crt")

class MyUser(MqttUser):
    host = "test.mosquitto.org"
    port = 8884
    tls_context = tls_context

    wait_time = between(0.01, 0.1)

    @task
    class MyTasks(TaskSet):

        def on_start(self):
            time.sleep(5)

        @task
        def say_hello(self):
            self.client.publish(
                "hello/locust", json.dumps({"message": "1" * 200000}).encode()
            )
```

## More Info

We could not reproduce the error using a standalone Paho-MQTT client. We tested the client with and without gevent:

```python
from gevent import monkey
import gevent

monkey.patch_all()

import json
import logging
import ssl
import paho.mqtt.client as mqtt

mqttc = mqtt.Client()

tls_context = ssl.SSLContext(ssl.PROTOCOL_TLS)
tls_context.load_cert_chain("client.crt", "client.key")
tls_context.load_verify_locations("mosquitto.org.crt")

mqttc.tls_set_context(tls_context)

mqttc.connect("test.mosquitto.org", 8884, 60)

mqttc.loop_start()

for _ in range(0, 1000000):
    mqttc.publish("class", json.dumps({"message": "1" * 200000}).encode(), qos=0)
    gevent.sleep(0.01)
``` 

Do you know which can be the source problem?

**Comment by cyberw** [comment] 2023-08-30 09:55
No idea, sorry. @tomasgareau do you have any idea?

**Comment by tomasgareau** [comment] 2023-08-30 18:48
Hmmm not sure either... it's not something I've encountered before.

Other places where I see it pop up seem to have "threading" as the common culprit (e.g., [miguelgrinberg/python-socketio](https://www.github.com/miguelgrinberg/python-socketio/issues/451), [this stackoverflow issue comment](https://stackoverflow.com/questions/60644221/ssl-exception-error1409e10fssl-routinesssl3-write-bytesbad-length#comment107328355_60644221)).

AFAIK `paho-mqtt` [_isn't_ thread-safe](https://www.github.com/eclipse/paho.mqtt.python/issues/358) and I do notice your traceback has a reference to `threading.py` (`File "/usr/lib/python3.11/threading.py", line 1038,`)...

I'm not familiar with how locust plugins hook into the locust runner but if one Paho MQTT client is being used in multiple threads (rather than a new client being created for each thread) that might be giving you grief.

---------------------

Other avenues that are a bit of a shot in the dark (don't expect them to fix it but can't hurt)
* use `ssl.PROTOCOL_TLS_CLIENT` rather than `ssl.PROTOCOL_TLS` -- looks like `ssl.PROTOCOL_TLS` is [deprecated since Python 3.10](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS)
* check that your openssl version is up-to-date

**Comment by cyberw** [comment] 2023-08-30 20:23
Is it possible (maybe even likely) that every user needs its own TLS context? Try creating it in the User constructor, so something like:

class MyUser(MqttUser):
    def __init__(self, environment: Environment):
        self.tls_context = ssl.SSLContext(ssl.PROTOCOL_TLS)
        self.tls_context.load_cert_chain("client.crt", "client.key")
        self.tls_context.load_verify_locations("mosquitto.org.crt")
        super().__init__(environment)
    ...

**Comment by joan-mido-qa** [comment] 2023-09-05 14:03
Thanks for your fast response. We tried both suggestions, but they did not work. We reproduced the issue by monkey patching the Paho Client with gevent. We had to wait longer to reproduce the error ( ~1400 Requests with Locust vs. ~6000 Requests without Locust ). We will open an issue to the gevent repository. We can close this issue. I will let you know any status updates about this topic. Thank you anyway, and sorry for the noise.

**Closed as not planned** 2023-09-05 14:22 UTC
